{% set name = "heartrate" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/heartrate-{{ version }}.tar.gz
  sha256: a51841684521be6eaaad6ed7f03a3834f40a6492b7c823e9f50efe41ac5aa077

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - asttokens
    - executing
    - flask
    - pygments
    - python >=3.6

test:
  imports:
    - heartrate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alexmojaki/heartrate
  summary: Simple real time visualisation of the execution of a Python program.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
